@localhost=localhost:4004/odata/v4/main

@id=e3658bcd-2f99-47c7-ae07-0846f01ea7a8

GET http://{{localhost}}/Customers
Content-Type: application/json

###

POST http://{{localhost}}/Customers
Content-Type: application/json

{
    "id":"{{id}}",
    "firstName":"Enzo",
    "lastName":"De Jesus",
    "email":"enzoss23@gmail.com"
}

###

DELETE http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "Joelson",
    "email":"joelson11@hotmail.com"
}


###

PATCH http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "Erick",
    "email":"erickss174@gmail.com"
}

# entity Customer {
#     key id: UUID;
#         firstName: String(20);
#         lastName: String(100);
#         email: String(255);   
# }

###
GET http://{{localhost}}/Customers?$filter=endswith(firstName, '-24383571')
Content-Type: application/json

###

# Buscando dados com $search
GET http://{{localhost}}/Customers?$search=374
Content-Type: application/json

###

# Ordenando dados com $orderby
GET http://{{localhost}}/Customers?$orderby=firstName,lastName desc
Content-Type: application/json
