@localhost=localhost:4004/odata/v4/main
@id=c23a8804-d5a0-49fe-aa79-3a0a1aba2ca4
@customerId=e3658bcd-2f99-47c7-ae07-0846f01ea7a8
@customerIdV=13188374-7299-4cce-bc04-b18d1f3548ff
@productId1=16569095-cebf-47fe-b199-b74a689dc76f
# Sem estoque
@productId2=14884777-50c9-45a0-ac1b-ff785704b620

GET http://{{localhost}}/SalesOrderHeaders
 #?$filter=id eq {{id}}&$expand=items
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345
###

POST http://localhost:4004/odata/v4/main/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345

{
    "id": "{{id}}",
    "customer_id":"{{customerIdV}}",
        "items": [
        {
            "id":"a95c1e7d-45d1-4409-90b9-725a962b9c09",
            "header_id":"{{id}}",
            "product_id":"{{productId2}}",
            "quantity": 10,
            "price": 1000
        },

        {
            "id":"34e9db1a-8799-4711-b83f-d60a148840fb",
            "header_id":"{{id}}",
            "product_id":"{{productId2}}",
            "quantity": 5,
            "price": 5000
        }        
    ] 
}

###

DELETE http://localhost:4004/odata/v4/main/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345
###

PUT http://localhost:4004/odata/v4/main/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345
{
    "modifiedBy": "teste"
}


# entity SalesOrderHeaders: managed {
#     key id: UUID;
#         customer: Association to Customers;
#         totalAmount: Decimal(15,2);
#         items: Composition of many SalesOrderItems on items.header = $self; //$self referenciando a propria entidade
# }

# entity SalesOrderItems {
#     key id: UUID;
#         header: Association to SalesOrderHeaders;
#         product: Association to Products;
#         quantity: Integer;
#         price: Decimal(15,2);
# }

# entity Customers {
#     key id: UUID;
#         firstName: String(20);
#         lastName: String(100);
#         email: String(255);   
# }

# entity Products {
#     key id: UUID;
#         name: String(255);
#         price: Decimal(15,2);
# }

###
# Busca por pedidos maiores ou iguais a 2 milhões valor
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000&$expand=items
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345
###
# Busca por pedidos maiores ou iguais a 200k valor
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 200000&$expand=items
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345
###
# Expandindo os items, produto e customers
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 200000&$expand=items($expand=product;$filter=quantity le 30),customer
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345
###
# Selecionar somente customer e id do sales order header
GET http://{{localhost}}/SalesOrderHeaders?$select=customer&$expand=customer($select=email)
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345
###
# Descobrindo a quantidade de registros
GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345
###
# Paginando os Registros
GET http://{{localhost}}/SalesOrderHeaders?$skip=5&$top=3   
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345
###
# Buscando dados com $search
GET http://{{localhost}}/SalesOrderHeaders?$search=org&$filter=totalAmount eq 12853185.15
Content-Type: application/json
Authorization: Basic enzo:Inicial@12345